In [14]:
#1.5H
import numpy as np
import pandas as pd
import collections

df = pd.read_csv("highDdata.csv")
N = 1000
df = df[1:N+1]
data = np.array(df)
data = data[:, 6:data.shape[1]]
print(data)
from sklearn.cluster import KMeans
 
num_clusters = 2
km_cluster = KMeans(n_clusters=num_clusters, max_iter=300, n_init=40, \
                    init='k-means++',n_jobs=-1)

#返回各自文本的所被分配到的类索引
result = km_cluster.fit_predict(data)
show = np.column_stack((np.array(df)[:,1], result))
show = pd.DataFrame(show, columns=["name", "class"])
show
# for i in range(N):
#     print(df.iat[i,1], result[i])





[[1.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 0.0]
 ...
 [1.0 0.0 0.0 ... 1.0 0.0 1.0]
 [0.0 0.0 0.0 ... 1.0 0.0 1.0]
 [1.0 0.0 0.0 ... 1.0 0.0 1.0]]


0  1
0                              Peanuts  1
1               Organic Salted Nut Mix  0
2                      Organic Polenta  0
3    Breadshop Honey Gone Nuts Granola  0
4        Organic Long Grain White Rice  0
..                                 ... ..
995                     Flavored Mints  1
996                Summer Ice Pop Mint  1
997                         Freshmints  1
998                        Fruit Mints  0
999                         Freshmints  1

[1000 rows x 2 columns]